import PointsAllTime from "@/components/points/all-time";
import PointsBalance from "@/components/points/balance";
import { RecentTransactions } from "@/components/transactions/recent-txns";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { WalletsList } from "@/components/wallets/wallets-list";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className="max-w-7xl mx-auto pt-20 flex flex-col gap-4">
        <div className="grid grid-cols-2 gap-4">
          <WalletsList />
          <RecentTransactions />
        </div>

        <div className="grid grid-cols-4 gap-4">
          <PointsAllTime />
          <PointsBalance />
          <Alert variant="success" className="col-span-2">
            <AlertTitle>All good!</AlertTitle>
            <AlertDescription>
              You have no transactions that need your attention right now.
            </AlertDescription>
          </Alert>
        </div>
      </main>
    </div>
  );
};

export default Home;
